- name: Configure /etc/hosts
  hosts: all
  become: yes

  tasks:
    - name: Configure /etc/hosts
      template:
        src: etc-hosts.j2
        dest: /etc/hosts
        owner: root
        group: root
        mode: '0644'
