---
- name: Join Kubernetes cluster with kubeadm
  hosts: knodes
  become: yes
  tasks:
    - name: Join the node to the cluster
      ansible.builtin.command:
        cmd: "{{ hostvars['k8s-control.cluster01.frop.org'].kubeadm_join_command }}"
      register: join_result
      ignore_errors: yes

    - name: Display kubeadm join output
      ansible.builtin.debug:
        msg: "{{ join_result.stdout }}"

    - name: Ensure kubelet is started and enabled
      ansible.builtin.systemd:
        name: kubelet
        state: started
        enabled: yes
      when: join_result.rc == 0

