- name: Stop and remove all containerd containers
  hosts: all
  become: true
  tasks:

    - name: Collect all containerd tasks
      ansible.builtin.command: "ctr -n k8s.io tasks list -q"
      register: task_ids
      changed_when: false

    - name: Kill each task  # noqa no-changed-when
      ansible.builtin.command: "ctr -n k8s.io tasks kill {{ item }}"
      loop: "{{ task_ids.stdout_lines }}"
      when: task_ids.stdout_lines | length > 0

    - name: List and remove all containerd containers
      ansible.builtin.command: "ctr -n k8s.io containers list -q"
      register: container_ids
      changed_when: false

    - name: Remove each container  # noqa no-changed-when
      ansible.builtin.command: "ctr -n k8s.io containers rm {{ item }}"
      loop: "{{ container_ids.stdout_lines }}"
      when: container_ids.stdout_lines | length > 0
