- name: Install and remove packages
  hosts: all
  become: yes

  tasks:
    - name: Install required packages
      apt:
        name:
          - dnsmasq
          - nginx
          - python3-certbot-dns-digitalocean
          - python3-certbot-nginx
        state: present
        update_cache: yes
