- name: Install and remove packages
  hosts: all
  become: yes

  tasks:
    - name: Install required packages
      apt:
        name:
          - containerd.io
        state: present
        update_cache: yes
