---
- name: Install kubeadm, kubelet, and kubectl
  hosts: all
  become: yes
  tasks:
    - name: Install kubeadm, kubelet, and kubectl
      ansible.builtin.package:
        name:
          - containerd.io
          - kubeadm
          - kubelet
          - kubectl
        state: present

    - name: Ensure kubelet is enabled and started
      ansible.builtin.systemd:
        name: kubelet
        state: started
        enabled: yes
