- name: Set hostname based on inventory hostname
  hosts: all
  become: yes

  tasks:
    - name: Set system hostname
      hostname:
        name: "{{ inventory_hostname }}"
      tags: hostname

    - name: Update /etc/hostname
      copy:
        dest: /etc/hostname
        content: "{{ inventory_hostname }}\n"
        owner: root
        group: root
        mode: '0644'
      tags: hostname
