- name: Configure sysctl parameters
  hosts: all
  become: true

  tasks:
    - name: Set sysctl parameters
      ansible.posix.sysctl:
        name: "{{ item.name }}"
        value: "{{ item.value }}"
        state: present
        sysctl_file: /etc/sysctl.d/50-ansible-managed.conf
        reload: true
      loop:
        - { name: "vm.swappiness", value: "100" }
        - { name: "net.ipv4.ip_forward", value: "1" }
        - { name: "net.ipv4.conf.all.arp_announce", value: "2" }
        - { name: "net.ipv4.conf.all.arp_ignore", value: "2" }
        - { name: "net.ipv4.conf.all.arp_filter", value: "1" }
        - { name: "net.ipv6.conf.all.forwarding", value: "1" }
